services:
  replica0:
    environment:
      - replica_id=0
      - contractor_ip=contractor0
    build:
      context: .
      dockerfile: replica.dockerfile
    ports:
      - "127.0.0.1:8090:8090"
  replica1:
    environment:
      - replica_id=1
      - contractor_ip=contractor1
    build:
      context: .
      dockerfile: replica.dockerfile
    ports:
      - "127.0.0.1:8091:8090"
  replica2:
    environment:
      - replica_id=2
      - contractor_ip=contractor1
    build:
      context: .
      dockerfile: replica.dockerfile
    ports:
      - "127.0.0.1:8092:8090"
  replica3:
    environment:
      - replica_id=3
      - contractor_ip=contractor1
    build:
      context: .
      dockerfile: replica.dockerfile
    ports:
      - "127.0.0.1:8093:8090"
  replica4:
    environment:
      - replica_id=4
      - contractor_ip=contractor4
    build:
      context: .
      dockerfile: replica.dockerfile
    ports:
      - "127.0.0.1:8094:8090"
  replica5:
    environment:
      - replica_id=5
      - contractor_ip=contractor4
    build:
      context: .
      dockerfile: replica.dockerfile
    ports:
      - "127.0.0.1:8095:8090"
  replica6:
    environment:
      - replica_id=6
      - contractor_ip=contractor4
    build:
      context: .
      dockerfile: replica.dockerfile
    ports:
      - "127.0.0.1:8096:8090"
  replica7:
    environment:
      - replica_id=7
      - contractor_ip=contractor4
    build:
      context: .
      dockerfile: replica.dockerfile
    ports:
      - "127.0.0.1:8097:8090"


  proxy0:
    command: sh -c "sleep 100; java -jar /app.jar;"
    environment:
      - proxy_id=0
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8080:8080"


  proxy1:
    command: sh -c "sleep 100; java -jar /app.jar;"
    environment:
      - proxy_id=1
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8081:8080"


  proxy2:
    command: sh -c "sleep 100; java -jar /app.jar;"
    environment:
      - proxy_id=2
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8082:8080"

  proxy3:
    command: sh -c "sleep 100; java -jar /app.jar;"
    environment:
      - proxy_id=3
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "127.0.0.1:8083:8080"


  contractor0:
    command: sh -c "sleep 100; java -jar /app.jar;"
    environment:
      - spring_datasource_url=jdbc:h2:tcp://replica0:8023/mem:state
    build:
      context: .
      dockerfile: contractor.dockerfile


  contractor1:
    command: sh -c "sleep 100; java -jar /app.jar;"
    environment:
      - spring_datasource_url=jdbc:h2:tcp://replica1:8023/mem:state
    build:
      context: .
      dockerfile: contractor.dockerfile


  contractor4:
    command: sh -c "sleep 100; java -jar /app.jar;"
    environment:
      - spring_datasource_url=jdbc:h2:tcp://replica4:8023/mem:state
    build:
      context: .
      dockerfile: contractor.dockerfile
